### ISSUE TITLE
Please merge develop to master

### ISSUE THREAD

**Issue by ivelfan** [1337/jquery_viewport#5]
Hello,

Can you please update master branch with latest commit on develop ?

Thanks.

**Comment by ivelfan** [comment]
Up.

**Comment by 1337** [comment]
Ok

**Comment by graingert** [comment]
@1337 can you get rid of the develop branch?

**Comment by 1337** [comment]
@graingert What for?

**Comment by graingert** [comment]
@1337 it's confusing to have two branches for contributors to merge into.

**Comment by 1337** [comment]
@graingert Developers contribute to the develop branch.

I can make that clear instead of deleting the develop branch.

**Comment by graingert** [comment]
@1337 why not the master branch like every other github project (github defaults to PRs going into develop)

**Comment by graingert** [comment]
What advantage is this extra branch doing? As far as I can see it's extra complication that you don't need

**Comment by 1337** [comment]
It might come across as bizarre, but I like that complexity.

**Comment by graingert** [comment]
>  but I like that complexity

lol ok

**Comment by ivelfan** [comment]
Thks
